// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-CU7YXGDdHt6AgrzYe-PNoVR7j-PWOI',
    appId: '1:693069361385:web:503f424650ceaa4c698078',
    messagingSenderId: '693069361385',
    projectId: 'food-delivery-express-7f7fc',
    authDomain: 'food-delivery-express-7f7fc.firebaseapp.com',
    storageBucket: 'food-delivery-express-7f7fc.appspot.com',
    measurementId: 'G-Y78RVMK0SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRrRS9SegKYRAFhTn_dya96QvV6ZZfinQ',
    appId: '1:693069361385:android:c44b4e645647f7b0698078',
    messagingSenderId: '693069361385',
    projectId: 'food-delivery-express-7f7fc',
    storageBucket: 'food-delivery-express-7f7fc.appspot.com',
  );
}
